@startuml
'https://plantuml.com/sequence-diagramskinparam sequenceArrowThickness 2
skinparam roundcorner 20
skinparam maxmessagesize 0
skinparam sequenceParticipant underline
skinparam sequence {
ArrowColor black
ActorBorderColor #black
LifeLineBorderColor black
LifeLineBackgroundColor white
ParticipantBorderColor black
ParticipantBackgroundColor #transparent
ParticipantFontName Aapex
ParticipantFontSize 14
ParticipantFontColor black
ActorBackgroundColor #transparent
ActorFontColor black
ActorFontSize 14
ActorFontName Aapex
}
autonumber

participant "selectedProject: Project" as project
participant ": SprintDatesMapper" as mapper
participant "dto : CreateSprintDto" as dto

project -> mapper : sprintTime = getSprintTime(dto)
activate mapper
group ref
mapper -> dto : startDateStg = sprintStartDateDto
mapper -> mapper : startDate = getDate(startDateStg)
mapper -> dto : endDateStg = endDateDto
mapper -> mapper : endDate = getDate(endDateStg)
create participant "sprintTime : Time" as time
mapper -> time : create(startDate,endDate)
end ref

@enduml