@startuml
skinparam actor {
BackgroundColor #white
ArrowColor #black
BorderColor #black
}
skinparam usecase {
BackgroundColor #white
ArrowColor #black
BorderColor #black
}
actor Director as Director
usecase (UC005 - I want to register/create a new project.) as UC

:Director: -- UC
@enduml




