@startuml
autonumber
actor Administrator #FFFFFF
participant "Project Management UI" #FFFFFF
participant "Project Management Business Logic" #FFFFFF
participant "SGBD" #FFFFFF

activate "Administrator"
"Administrator" -> "Project Management UI" ++: Initiates process to create a new Profile

"Project Management UI" --> "Administrator" : Requests the necessary information to create a new Profile
deactivate "Project Management UI"

"Administrator" -> "Project Management UI" ++: Inserts new profile description

"Project Management UI" -> "Project Management Business Logic" ++: create new Profile (REST)

"Project Management Business Logic" -> "SGBD" ++ : does profile exist already?

"SGBD" --> "Project Management Business Logic" : false
deactivate "SGBD"

"Project Management Business Logic"  -> "SGBD" ++: save new Profile

"SGBD" --> "Project Management Business Logic"  : return representation of saved Profile
deactivate

"Project Management Business Logic" -> "Project Management UI" : Inform operation result (REST - json and Http Status)
deactivate

"Project Management UI" -> "Administrator" : Show newly created Profile
deactivate

@enduml