@startuml
'https://plantuml.com/sequence-diagramskinparam sequenceArrowThickness 2
skinparam roundcorner 20
skinparam maxmessagesize 0
skinparam sequenceParticipant underline

skinparam sequence {
ArrowColor black
ActorBorderColor #black
LifeLineBorderColor black
LifeLineBackgroundColor white

ParticipantBorderColor black
ParticipantBackgroundColor #transparent
ParticipantFontName Aapex
ParticipantFontSize 14
ParticipantFontColor black

ActorBackgroundColor #transparent
ActorFontColor black
ActorFontSize 14
ActorFontName Aapex
}
autonumber
actor "TeamMember / ScrumMaster" as TMSM
participant ": System" as System
Activate TMSM
Activate System
TMSM -> System :  Create task outside the scope of a user story
TMSM -> System :  Enters data: taskName, taskDescription, taskStartDate, taskEndDate, taskPrecedence, taskResponsible, typeOfTask, projectCode, sprintNumber, taskEstimateEffort
System -> System : createTask
System --> TMSM : Task

@enduml