@startuml
skinparam actor {
BackgroundColor #white
ArrowColor #black
BorderColor #black
}
skinparam usecase {
BackgroundColor #white
ArrowColor #black
BorderColor #black
}
actor TeamMember
usecase (UC031-Create a task in a user story.)

:TeamMember: -- (UC031-Create a task in a user story.)
@enduml