#!/bin/bash
USERS_IN_SERVER=/var/www/dataManagament/userStore
error_response() {
  echo "Status: 400 Bad Request"
  echo "Content-type: text/plain"
  echo ""
  echo "ERROR: ${1}"
  exit
}

### Get content from JSON into global variables
if [ -n "$CONTENT_LENGTH" ]; then
  eval "$(jq -r '@sh "USERNAME_JSON=\(.username) EMAIL_JSON=\(.email) FUNCTION_JSON=\(.function) PASS_JSON=\(.password)"')"
else
  error_response "No content found on the request"
fi

if [ "$CONTENT_LENGTH" == "0" ]; then
  error_response "No content found on the request"
fi

### If the wrong method is used
if [ "$REQUEST_METHOD" != "POST" ]; then
  error_response "Invalid method. The only supported method is POST."
fi

### Check if email is already taken
EMAIL_FOUND=0
if [ -d "$USERS_IN_SERVER/$EMAIL_JSON" ]; then
   EMAIL_FOUND=1
fi

if [ $EMAIL_FOUND -eq 1 ]; then
  error_response "Email already taken."
fi

### Hash pass
HASHCODE=$((0x$(sha1sum <<<"$PASS_JSON")0))

### Generate random code between 1000 and 9999
CODE=$((1000 + $RANDOM % 9999))

### Create User
mkdir -p "$USERS_IN_SERVER/$EMAIL_JSON"
echo "$HASHCODE" > "$USERS_IN_SERVER/$EMAIL_JSON/pass"
echo "$USERNAME_JSON" >> "$USERS_IN_SERVER/$EMAIL_JSON/username"
echo "$FUNCTION_JSON" >> "$USERS_IN_SERVER/$EMAIL_JSON/function"
echo "0" >> "$USERS_IN_SERVER/$EMAIL_JSON/status" 
mkdir -p "$USERS_IN_SERVER/$EMAIL_JSON/userProfiles"
touch "$USERS_IN_SERVER/$EMAIL_JSON/userProfiles/Visitor"
echo "$CODE" >> "$USERS_IN_SERVER/$EMAIL_JSON/activation"

### Send Activation code
echo -e "From: SCOMRED <no-reply@dei.isep.ipp.pt>\r\nSubject: SCOMRED Group5 Project Management Solutions - user activation code\r\n\r\nWelcome to Project Management solutions $USERNAME_JSON! To activate your account you need to introduce the following code in our platform.\nActivation code: $CODE"|ssmtp $EMAIL_JSON

echo "Content-type: text/plain"
echo ""
echo "Account Successfully Created"
###
