#!/bin/bash
USERS_IN_SERVER=/var/www/dataManagament/userStore
PROFILES_IN_SERVER=/var/www/dataManagament/profileStore
REQUESTS_IN_SERVER=/var/www/dataManagament/requestStore
error_response() {
  echo "Status: 400 Bad Request"
  echo "Content-type: text/plain"
  echo ""
  echo "ERROR: ${1}"
  exit
}

### Get content from JSON into global variables
if [ -n "$CONTENT_LENGTH" ]; then
  eval "$(jq -r '@sh "EMAIL_JSON=\(.email) PROFILE_JSON=\(.profile) PASS_JSON=\(.password)"')"
else
  error_response "No content found on the request"
fi

if [ "$CONTENT_LENGTH" == "0" ]; then
  error_response "No content found on the request"
fi

### If the wrong method is used
if [ "$REQUEST_METHOD" != "POST" ]; then
  error_response "Invalid method. The only supported method is POST."
fi

### Check profiles in system
PROFILE_FOUND=0
if [ -f "$PROFILES_IN_SERVER/$PROFILE_JSON" ]; then
  PROFILE_FOUND=1
fi

if [ $PROFILE_FOUND -eq 0 ]; then
  error_response "Profile doesn't exist in server"
fi

### Check if User exists, is active, doesn't already have the requested Profile and has the Visitor Profile
EMAIL_FOUND=0
if [ -d "$USERS_IN_SERVER/$EMAIL_JSON" ]; then
  EMAIL_FOUND=1
fi

if [ $EMAIL_FOUND -eq 0 ]; then
  error_response "User doesn't exist in server"
fi

if [ "0" == $(cat $USERS_IN_SERVER/$EMAIL_JSON/status) ]; then
  error_response "User account is not active."
fi

### Hash current password and compare with the one stored in the system
PASS_MATCH=0
CURRENT_HASH=$(cat "$USERS_IN_SERVER"/"$EMAIL_JSON"/pass)
CLIENT_HASH=$((0x$(sha1sum <<<"$PASS_JSON")0))
if [ "$CURRENT_HASH" = "$CLIENT_HASH" ]; then
  PASS_MATCH=1
fi

if [ $PASS_MATCH -eq 0 ]; then
  error_response "The password you have entered is incorrect."
fi

USER_HAS_VISITOR_PROFILE=0
if [ -f "$USERS_IN_SERVER/$EMAIL_JSON/userProfiles/Visitor" ]; then
  USER_HAS_VISITOR_PROFILE=1
fi

if [ $USER_HAS_VISITOR_PROFILE == 0 ]; then
  error_response "User doesn't have the Visitor profile associated."
fi

PROFILE_ALREADY_ASSOCIATED=0
if [ -f "$USERS_IN_SERVER/$EMAIL_JSON/userProfiles/$PROFILE_JSON" ]; then
  PROFILE_ALREADY_ASSOCIATED=1
fi

if [ $PROFILE_ALREADY_ASSOCIATED == 1 ]; then
  CURRENT_USER_PROFILES=$(ls -m $USERS_IN_SERVER/$EMAIL_JSON/userProfiles)
  error_response "User already has the selected profile. Current user profiles for this user are: $CURRENT_USER_PROFILES"
fi

### Check if there are no Requests in System
IS_REQUEST_IN_SERVER=0
NEW_REQUEST_PATH="$REQUESTS_IN_SERVER/$EMAIL_JSON"

if [ "0" == "$(cat "$NEW_REQUEST_PATH/requestedProfiles/$PROFILE_JSON")" ]; then
  IS_REQUEST_IN_SERVER=1
fi

if [ $IS_REQUEST_IN_SERVER == 1 ]; then
  error_response "Request already in System"
fi

mkdir -p "$NEW_REQUEST_PATH/requestedProfiles"
echo "0" >"$NEW_REQUEST_PATH/requestedProfiles/$PROFILE_JSON"

echo "Content-type: text/plain"
echo ""
echo "Request Successfully Created"
###

