#!/bin/bash
USERS_IN_SERVER=/var/www/dataManagament/userStore
PROFILES_IN_SERVER=/var/www/dataManagament/profileStore
REQUESTS_IN_SERVER=/var/www/dataManagament/requestStore

error_response() {
  echo "Status: 400 Bad Request"
  echo "Content-type: text/plain"
  echo ""
  echo "ERROR: ${1}"
  exit
}

### Get content from JSON into global variables
if [ -n "$CONTENT_LENGTH" ]; then
  eval "$(jq -r '@sh "ADMIN_EMAIL_JSON=\(.adminEmail) PASS_ADMIN_JSON=\(.adminPass) EMAIL_JSON=\(.email) PROFILE_JSON=\(.newProfile)"')"
else
  error_response "No content found on the request"
fi

if [ "$CONTENT_LENGTH" == "0" ]; then
  error_response "No content found on the request"
fi

### If the wrong method is used
if [ "$REQUEST_METHOD" != "POST" ]; then
  error_response "Invalid method. The only supported method is POST."
fi

### Check if Admin exists and has the Administrator profile
ADMIN_EMAIL_FOUND=0
if [ -d "$USERS_IN_SERVER/$ADMIN_EMAIL_JSON" ]; then
   ADMIN_EMAIL_FOUND=1
fi

if [ $ADMIN_EMAIL_FOUND -eq 0 ]; then
  error_response "Admin email doesn't exist in server"
fi

ADMIN_HAS_ADMIN_PROFILE=0
if [ -f "$USERS_IN_SERVER/$ADMIN_EMAIL_JSON/userProfiles/Administrator" ] ; then
   ADMIN_HAS_ADMIN_PROFILE=1
fi

if [ $ADMIN_HAS_ADMIN_PROFILE == 0 ]; then
  error_response "Admin email inserted doesn't have the Administrator profile associated."
fi

if [ $EMAIL_FOUND -eq 0 ]; then
  error_response "The email you entered is not connected to an account. "
fi

### Hash current password and compare with the one stored in the system
PASS_MATCH=0
CURRENT_HASH=$(cat "$USERS_IN_SERVER"/"$ADMIN_EMAIL_JSON"/pass)
CLIENT_HASH=$((0x$(sha1sum <<<"$PASS_ADMIN_JSON")0))
if [ "$CURRENT_HASH" = "$CLIENT_HASH" ]; then
  PASS_MATCH=1
fi

if [ $PASS_MATCH -eq 0 ]; then
  error_response "The password you have entered is incorrect."
fi

### Check if User exists
EMAIL_FOUND=0
if [ -d "$USERS_IN_SERVER/$EMAIL_JSON" ]; then
   EMAIL_FOUND=1
fi

if [ $EMAIL_FOUND -eq 0 ]; then
  error_response "User doesn't exist in server"
fi

### Check profiles in system
PROFILE_FOUND=0
if [ -f "$PROFILES_IN_SERVER/$PROFILE_JSON" ]; then
   PROFILE_FOUND=1
fi

if [ $PROFILE_FOUND -eq 0 ]; then
  error_response "Profile doesn't exist in server"
fi


### Update Profile
EXISTING_PROFILE=0

if [ -f "$USERS_IN_SERVER/$EMAIL_JSON/userProfiles/$PROFILE_JSON" ] ; then
    EXISTING_PROFILE=1
fi

if [ $EXISTING_PROFILE == 1 ]; then
  error_response "User already has the selected profile."
fi


touch "$USERS_IN_SERVER/$EMAIL_JSON/userProfiles/$PROFILE_JSON"


### Check if there are no Requests in System. If there are, change value to 1
NEW_REQUEST_PATH="$REQUESTS_IN_SERVER/$EMAIL_JSON"

if [ "0" == "$(cat "$NEW_REQUEST_PATH/requestedProfiles/$PROFILE_JSON")" ] ; then
    echo "1" > "$NEW_REQUEST_PATH/requestedProfiles/$PROFILE_JSON"
fi


echo "Content-type: text/plain"
echo ""
echo "Update was Successful"
###
