#!/bin/bash
USERS_IN_SERVER=/var/www/dataManagament/userStore


error_response() {
  echo "Status: 400 Bad Request"
  echo "Content-type: text/plain"
  echo ""
  echo "ERROR: ${1}"
  exit
}

### Get content from JSON into global variables
if [ -n "$CONTENT_LENGTH" ]; then
  eval "$(jq -r '@sh "EMAIL_JSON=\(.email) OLD_PASS_JSON=\(.oldPass) NEW_PASS_JSON=\(.newPass)"')"
else
  error_response "No content found on the request"
fi

if [ "$CONTENT_LENGTH" == "0" ]; then
  error_response "No content found on the request"
fi

### If the wrong method is used
if [ "$REQUEST_METHOD" != "POST" ]; then
  error_response "Invalid method. The only supported method is POST."
fi

### Check if User exists 
EMAIL_FOUND=0
if [ -d "$USERS_IN_SERVER/$EMAIL_JSON" ]; then
   EMAIL_FOUND=1
fi

if [ $EMAIL_FOUND -eq 0 ]; then
  error_response "The email you entered is not connected to an account. "
fi

### Hash current password and compare with the one stored in the system
PASS_MATCH=0
CURRENT_HASH=$(cat "$USERS_IN_SERVER"/"$EMAIL_JSON"/pass)
CLIENT_HASH=$((0x$(sha1sum <<<"$OLD_PASS_JSON")0))
if [ "$CURRENT_HASH" = "$CLIENT_HASH" ]; then
  PASS_MATCH=1
fi

if [ $PASS_MATCH -eq 0 ]; then
  error_response "The password you have entered is incorrect."
fi

### Update Password
NEW_HASH=$((0x$(sha1sum <<<"$NEW_PASS_JSON")0))
echo "$NEW_HASH" > "$USERS_IN_SERVER/$EMAIL_JSON/pass"
echo "Content-type: text/plain"
echo ""
echo "Update was Successful"
###
