#!/bin/bash
USERS_IN_SERVER=/var/www/dataManagament/userStore
error_response() {
  echo "Status: 400 Bad Request"
  echo "Content-type: text/plain"
  echo ""
  echo "ERROR: ${1}"
  exit
}

### Get content from JSON into global variables
if [ -n "$CONTENT_LENGTH" ]; then
  eval "$(jq -r '@sh "EMAIL_JSON=\(.email) PASS_JSON=\(.pass) ACTIVE_EMAIL_JSON=\(.user)"')"
else
  error_response "No content found on the request"
fi

if [ "$CONTENT_LENGTH" == "0" ]; then
  error_response "No content found on the request"
fi

### If the wrong method is used
if [ "$REQUEST_METHOD" != "POST" ]; then
  error_response "Invalid method. The only supported method is POST."
fi

### Check credentials
EMAIL_FOUND=0
if [ -d "$USERS_IN_SERVER/$EMAIL_JSON" ]; then
  EMAIL_FOUND=1
fi

if [ $EMAIL_FOUND -eq 0 ]; then
  error_response "The email you entered is not connected to an account."
fi

### Hash current password and compare with the one stored in the system
PASS_MATCH=0
CURRENT_HASH=$(cat "$USERS_IN_SERVER"/"$EMAIL_JSON"/pass)
CLIENT_HASH=$((0x$(sha1sum <<<"$PASS_JSON")0))
if [ "$CURRENT_HASH" = "$CLIENT_HASH" ]; then
  PASS_MATCH=1
fi

if [ $PASS_MATCH -eq 0 ]; then
  error_response "The password you have entered is incorrect."
fi

### Check for admin permissions
ADMIN=0
if [ -f "$USERS_IN_SERVER/$EMAIL_JSON/userProfiles/Administrator" ] ; then
   ADMIN=1
fi

if [ $ADMIN -eq 0 ]; then
  error_response "Input email doesn't have Administrator profile"
fi

### Find user's status and set status to active
REMOVED="The email you entered is not connected to an account."
while read line; do
  if [ "$line" == "$ACTIVE_EMAIL_JSON" ]; then
     echo "1" > "$USERS_IN_SERVER/$line/status"
     REMOVED="User was set to active."
  fi
done <<<"$(ls $USERS_IN_SERVER)"
echo "Content-type: text/plain"
echo ""
echo "$REMOVED"
###
