@startuml





class Email #FFFFFF {
	-email : string
	+getEmail() : string
}

class User #FFFFFF {
	-profile : Profile
	-email : Email
	+compareEmail(searchField) : boolean
	+compareProfile(searchField) : boolean
}


class Profile #FFFFFF {
	-designation : string
	+getProfileDesignation()
}


User "1" -- "1..*" Profile : has
Email "1" -- "1" User : has



@enduml