@startuml
autonumber
actor Director #FFFFFF
participant "Project Management System" #FFFFFF

activate "Director"
"Director" -> "Project Management System" ++: Initiates process to create a new Typology
"Project Management System" --> "Director" : Requests the necessary information to create a new Typology
deactivate

"Director" -> "Project Management System" ++: Inserts new typology description
"Project Management System" --> "Director" : Inform operation result and return information about the newly created Typology
deactivate

@enduml