@startuml
autonumber
actor Director #FFFFFF
participant "Project Management UI" #FFFFFF
participant "Project Management Business Logic" #FFFFFF
participant "SGBD" #FFFFFF

activate "Director"
"Director" -> "Project Management UI" ++: Initiates process to create a new Typology

"Project Management UI" --> "Director" : Requests the necessary information to create a new Typology
deactivate "Project Management UI"

"Director" -> "Project Management UI" ++: Inserts new Typology description

"Project Management UI" -> "Project Management Business Logic" ++: create new Typology

"Project Management Business Logic" -> "SGBD" ++ : does typology exists?

"SGBD" --> "Project Management Business Logic" : false
deactivate "SGBD"

"Project Management Business Logic"  -> "SGBD" ++: save new Typology

"SGBD" --> "Project Management Business Logic"  : return representation of saved Typology
deactivate

"Project Management Business Logic" -> "Project Management UI" : Inform operation result (json and Http Status)
deactivate

"Project Management UI" -> "Director" : Show newly created Typology
deactivate

@enduml