@startuml
autonumber
actor "Administrator"
participant "System"
activate "Administrator"
activate "System"
"Administrator"->"System" : Selects User (inserts email))
"System" -> "Administrator" : User exists
"Administrator"-> "System" : Activates User Account
"System" -> "Administrator" : Confirms that user is Activated
@enduml