@startuml
'https://plantuml.com/sequence-diagramskinparam sequenceArrowThickness 2
skinparam roundcorner 20
skinparam maxmessagesize 0
skinparam sequenceParticipant underline

skinparam sequence {
ArrowColor black
ActorBorderColor #black
LifeLineBorderColor black
LifeLineBackgroundColor white

ParticipantBorderColor black
ParticipantBackgroundColor #transparent
ParticipantFontName Aapex
ParticipantFontSize 14
ParticipantFontColor black

ActorBackgroundColor #transparent
ActorFontColor black
ActorFontSize 14
ActorFontName Aapex
}
autonumber

actor "Director" as D
participant ": System" as System
Activate D


activate System
D -> System :  Define a SM of a Project
System --> D : Requests Data (email, projectCode, sprintNumber)
deactivate System
D -> System :  Enters data
activate System
System -> System : associateScrumMaster
System --> D : Scrum Master Defined
deactivate System

@enduml